on: [pull_request]
name: test
jobs:
  checks:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cedrickring/golang-action@1.6.0
        name: test
        with:
          args: make test